title: Wilhel's Blog # The title of the blog
author: Wilhel Yu # Your name
# email:  # your email shown in the footer
url: https://wilhelyu.github.io # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Simple record of life.
favicon: "./favicon.ico" # set the favicon of the site
show_excerpts: false # set to true to show excerpts on the homepage
permalink: /:categories/:year/:title:output_ext
# timezone: Asia/Shanghai
highlighter: none

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "./assets/img/avatar.jpg" # avatar in about page
  about_you: Keep it simple. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter:
    github: wilhelyu
    rss: RSS
    # dribbble:
    # facebook: huangyz0918
    # flickr:
    # instagram:
    # linkedin: yizheng-huang
    # pinterest:
    # youtube:
    # youtube_channel:
    # youtube_channel_name:
    # telegram:
    # googleplus:
    # microdotblog:
    # reddit:

    # Mastodon instances
    # mastodon:
    # - username:
    #   instance:
    # - username:
    #   instance:

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-category-pages

excludes:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - LICENSE.txt

defaults:
  - scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts" # 以前的 `post`， 在 Jekyll 2.2 里。
    values:
      layout: "post"
      author: "Wilhel Yu"
